
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersapi
  description: Surf Forecast API Gateway
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=surferslookout'
spec:
  type: service
  lifecycle: experimental
  owner: surfer-crew
  system: test
  providesApis:
    - alpha/surfersapi-tap3.tanzu.rocks

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfer-crew
  description: Team focused on the Surfer system
spec:
  type: team
  profile:
    displayName: Surfer Crew
  parent: default-org
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: surfer-a
spec:
  profile:
    displayName: Surfer Dude A
  memberOf: [surfer-crew]

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test
  description: Tanzu Application Platform GUI System
spec:
  owner: default-team
